# Generated by Django 6.0.7 on 2026-08-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='sale',
        ),
        migrations.AddField(
            model_name='salesitem',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='sales.sales'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('khalti', 'Khalti'), ('esewa', 'Esewa')], default='esewa', max_length=20),
        ),
    ]
