# Generated by Django 6.0.7 on 2026-08-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salesitem_sale_salesitem_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='sales.sales'),
        ),
    ]
