# Generated by Django 6.0.7 on 2026-08-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesitem_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='sales',
        ),
        migrations.AddField(
            model_name='salesitem',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.sales'),
        ),
    ]
