# Generated by Django 6.0.7 on 2026-09-01 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_salesitem_sales_salesitem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.sales'),
        ),
    ]
