# Generated by Django 6.0.7 on 2026-09-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_salesitem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
