# Generated by Django 6.0.7 on 2026-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('DAMAGE', 'Damage'), ('EXPIRY', 'Expiry'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('STOCK_TRANSFER', 'Stock Transfer')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_txn',
            },
        ),
    ]
