# Generated by Django 6.0.7 on 2026-08-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('medicine', '0003_remove_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytxn',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicinebatch'),
        ),
    ]
