# Generated by Django 6.0.7 on 2026-08-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_purchase_verified',
            field=models.BooleanField(default=False),
        ),
    ]
